volumes:
  minio-data:
    driver: local

networks:
  modos-network:
    driver: bridge

services:

  nginx:
    image: nginx:1.23
    depends_on:
      - htsget
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    environment:
      - FUZON_PUBLIC_URL=${FUZON_PUBLIC_URL:-http://localhost/fuzon}
      - HTSGET_PUBLIC_URL=${HTSGET_PUBLIC_URL:-http://localhost/htsget}
      - S3_PUBLIC_URL=${S3_PUBLIC_URL:-http://localhost/s3/}
      - FUZON_LOCAL_URL=${FUZON_LOCAL_URL:-http://fuzon:8080}
      - HTSGET_LOCAL_URL=${HTSGET_LOCAL_URL:-http://htsget:8080}
      - MODOS_LOCAL_URL=${MODOS_LOCAL_URL:-http://modos-server:8000}
      - S3_LOCAL_URL=${S3_LOCAL_URL:-http://minio:9000}
    ports:
      - "80:80"
    networks:
      - modos-network

  minio:
    image: docker.io/bitnami/minio:2024
    ports:
      - "9000:9000" # api
      - "9001:9001" # console
    volumes:
      - minio-data:/bitnami/minio/data
    networks:
      - modos-network
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minio}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-miniosecret}
      - MINIO_SERVER_ACCESS_KEY=${MINIO_SERVER_ACCESS_KEY:-user}
      - MINIO_SERVER_SECRET_KEY=${MINIO_SERVER_SECRET_KEY:-pass}
      - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKET:-modos-demo:public}
      - MINIO_REGION=us-east-1


  htsget:
    build: ./htsget
    depends_on:
        - minio
    volumes:
      - ./htsget/config.toml.template:/htsget/config.toml.template:ro
    expose:
      - "8080" # ticket server
      - "8081" # data block server
    networks:
      - modos-network
    environment:
      - ENDPOINT=${S3_PUBLIC_URL:-http://minio:9000}
      - BUCKET=${S3_BUCKET:-modos-demo}
      - S3_ADDRESSING_STYLE=${S3_ADDRESSING_STYLE:-auto}
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER:-minio}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD:-miniosecret}
      - AWS_REGION=us-east-1
      - RUST_LOG=debug


  fuzon:
    build: ./fuzon
    volumes:
      - ./fuzon/config.json.template:/fuzon/config.json.template:ro
    expose:
      - "8080"
    networks:
      - modos-network


  modos-server:
    build: ./modos-server
    expose:
      - "8000"
    networks:
      - modos-network
    environment:
      - S3_LOCAL_URL=${S3_LOCAL_URL:-http://minio:9000}
      - S3_PUBLIC_URL=${S3_PUBLIC_URL:-http://localhost/s3}
      - HTSGET_LOCAL_URL=${HTSGET_LOCAL_URL:-http://htsget:8080}
      - S3_BUCKET=${S3_BUCKET:-modos-demo}
      - S3_ADDRESSING_STYLE=${S3_ADDRESSING_STYLE:-auto}
    command: uvicorn --host 0.0.0.0 --port 8000 --reload server:app
